/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgenticExperimentalRouteImport } from './routes/agentic-experimental'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnchorChunkRouteImport } from './routes/api/anchor-chunk'
import { Route as ApiPublicX402VerifyRouteImport } from './routes/api/public/x402-verify'
import { Route as ApiPublicX402SettleRouteImport } from './routes/api/public/x402-settle'
import { Route as ApiPublicX402ProxyRouteImport } from './routes/api/public/x402-proxy'
import { Route as ApiPublicX402ChallengeRouteImport } from './routes/api/public/x402-challenge'
import { Route as ApiPublicSepoliaPayStatusRouteImport } from './routes/api/public/sepolia-pay-status'
import { Route as ApiPublicSepoliaFulfillRouteImport } from './routes/api/public/sepolia-fulfill'
import { Route as ApiPublicEffectstreamStatusRouteImport } from './routes/api/public/effectstream-status'

const AgenticExperimentalRoute = AgenticExperimentalRouteImport.update({
  id: '/agentic-experimental',
  path: '/agentic-experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnchorChunkRoute = ApiAnchorChunkRouteImport.update({
  id: '/api/anchor-chunk',
  path: '/api/anchor-chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402VerifyRoute = ApiPublicX402VerifyRouteImport.update({
  id: '/api/public/x402-verify',
  path: '/api/public/x402-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402SettleRoute = ApiPublicX402SettleRouteImport.update({
  id: '/api/public/x402-settle',
  path: '/api/public/x402-settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402ProxyRoute = ApiPublicX402ProxyRouteImport.update({
  id: '/api/public/x402-proxy',
  path: '/api/public/x402-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402ChallengeRoute = ApiPublicX402ChallengeRouteImport.update({
  id: '/api/public/x402-challenge',
  path: '/api/public/x402-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSepoliaPayStatusRoute =
  ApiPublicSepoliaPayStatusRouteImport.update({
    id: '/api/public/sepolia-pay-status',
    path: '/api/public/sepolia-pay-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSepoliaFulfillRoute = ApiPublicSepoliaFulfillRouteImport.update({
  id: '/api/public/sepolia-fulfill',
  path: '/api/public/sepolia-fulfill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEffectstreamStatusRoute =
  ApiPublicEffectstreamStatusRouteImport.update({
    id: '/api/public/effectstream-status',
    path: '/api/public/effectstream-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/api/anchor-chunk': typeof ApiAnchorChunkRoute
  '/api/public/effectstream-status': typeof ApiPublicEffectstreamStatusRoute
  '/api/public/sepolia-fulfill': typeof ApiPublicSepoliaFulfillRoute
  '/api/public/sepolia-pay-status': typeof ApiPublicSepoliaPayStatusRoute
  '/api/public/x402-challenge': typeof ApiPublicX402ChallengeRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/api/public/x402-settle': typeof ApiPublicX402SettleRoute
  '/api/public/x402-verify': typeof ApiPublicX402VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/api/anchor-chunk': typeof ApiAnchorChunkRoute
  '/api/public/effectstream-status': typeof ApiPublicEffectstreamStatusRoute
  '/api/public/sepolia-fulfill': typeof ApiPublicSepoliaFulfillRoute
  '/api/public/sepolia-pay-status': typeof ApiPublicSepoliaPayStatusRoute
  '/api/public/x402-challenge': typeof ApiPublicX402ChallengeRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/api/public/x402-settle': typeof ApiPublicX402SettleRoute
  '/api/public/x402-verify': typeof ApiPublicX402VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/api/anchor-chunk': typeof ApiAnchorChunkRoute
  '/api/public/effectstream-status': typeof ApiPublicEffectstreamStatusRoute
  '/api/public/sepolia-fulfill': typeof ApiPublicSepoliaFulfillRoute
  '/api/public/sepolia-pay-status': typeof ApiPublicSepoliaPayStatusRoute
  '/api/public/x402-challenge': typeof ApiPublicX402ChallengeRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/api/public/x402-settle': typeof ApiPublicX402SettleRoute
  '/api/public/x402-verify': typeof ApiPublicX402VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentic-experimental'
    | '/api/anchor-chunk'
    | '/api/public/effectstream-status'
    | '/api/public/sepolia-fulfill'
    | '/api/public/sepolia-pay-status'
    | '/api/public/x402-challenge'
    | '/api/public/x402-proxy'
    | '/api/public/x402-settle'
    | '/api/public/x402-verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentic-experimental'
    | '/api/anchor-chunk'
    | '/api/public/effectstream-status'
    | '/api/public/sepolia-fulfill'
    | '/api/public/sepolia-pay-status'
    | '/api/public/x402-challenge'
    | '/api/public/x402-proxy'
    | '/api/public/x402-settle'
    | '/api/public/x402-verify'
  id:
    | '__root__'
    | '/'
    | '/agentic-experimental'
    | '/api/anchor-chunk'
    | '/api/public/effectstream-status'
    | '/api/public/sepolia-fulfill'
    | '/api/public/sepolia-pay-status'
    | '/api/public/x402-challenge'
    | '/api/public/x402-proxy'
    | '/api/public/x402-settle'
    | '/api/public/x402-verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticExperimentalRoute: typeof AgenticExperimentalRoute
  ApiAnchorChunkRoute: typeof ApiAnchorChunkRoute
  ApiPublicEffectstreamStatusRoute: typeof ApiPublicEffectstreamStatusRoute
  ApiPublicSepoliaFulfillRoute: typeof ApiPublicSepoliaFulfillRoute
  ApiPublicSepoliaPayStatusRoute: typeof ApiPublicSepoliaPayStatusRoute
  ApiPublicX402ChallengeRoute: typeof ApiPublicX402ChallengeRoute
  ApiPublicX402ProxyRoute: typeof ApiPublicX402ProxyRoute
  ApiPublicX402SettleRoute: typeof ApiPublicX402SettleRoute
  ApiPublicX402VerifyRoute: typeof ApiPublicX402VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agentic-experimental': {
      id: '/agentic-experimental'
      path: '/agentic-experimental'
      fullPath: '/agentic-experimental'
      preLoaderRoute: typeof AgenticExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anchor-chunk': {
      id: '/api/anchor-chunk'
      path: '/api/anchor-chunk'
      fullPath: '/api/anchor-chunk'
      preLoaderRoute: typeof ApiAnchorChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-verify': {
      id: '/api/public/x402-verify'
      path: '/api/public/x402-verify'
      fullPath: '/api/public/x402-verify'
      preLoaderRoute: typeof ApiPublicX402VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-settle': {
      id: '/api/public/x402-settle'
      path: '/api/public/x402-settle'
      fullPath: '/api/public/x402-settle'
      preLoaderRoute: typeof ApiPublicX402SettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-proxy': {
      id: '/api/public/x402-proxy'
      path: '/api/public/x402-proxy'
      fullPath: '/api/public/x402-proxy'
      preLoaderRoute: typeof ApiPublicX402ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-challenge': {
      id: '/api/public/x402-challenge'
      path: '/api/public/x402-challenge'
      fullPath: '/api/public/x402-challenge'
      preLoaderRoute: typeof ApiPublicX402ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sepolia-pay-status': {
      id: '/api/public/sepolia-pay-status'
      path: '/api/public/sepolia-pay-status'
      fullPath: '/api/public/sepolia-pay-status'
      preLoaderRoute: typeof ApiPublicSepoliaPayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sepolia-fulfill': {
      id: '/api/public/sepolia-fulfill'
      path: '/api/public/sepolia-fulfill'
      fullPath: '/api/public/sepolia-fulfill'
      preLoaderRoute: typeof ApiPublicSepoliaFulfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/effectstream-status': {
      id: '/api/public/effectstream-status'
      path: '/api/public/effectstream-status'
      fullPath: '/api/public/effectstream-status'
      preLoaderRoute: typeof ApiPublicEffectstreamStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticExperimentalRoute: AgenticExperimentalRoute,
  ApiAnchorChunkRoute: ApiAnchorChunkRoute,
  ApiPublicEffectstreamStatusRoute: ApiPublicEffectstreamStatusRoute,
  ApiPublicSepoliaFulfillRoute: ApiPublicSepoliaFulfillRoute,
  ApiPublicSepoliaPayStatusRoute: ApiPublicSepoliaPayStatusRoute,
  ApiPublicX402ChallengeRoute: ApiPublicX402ChallengeRoute,
  ApiPublicX402ProxyRoute: ApiPublicX402ProxyRoute,
  ApiPublicX402SettleRoute: ApiPublicX402SettleRoute,
  ApiPublicX402VerifyRoute: ApiPublicX402VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
